### ISSUE TITLE
Subscript and superscript

### ISSUE THREAD

**Issue by MoeAfkani** [guillaume-elambert/Scholar-Scraper-Wordpress-Plugin#1]
Publications with Subscript and/or superscript in their title doesn't appear properly in the result json file!

**Comment by guillaume-elambert** [comment]
Hello, after looking into the issue, it seems that the problem is caused by the ["scholarly" Python package](https://github.com/scholarly-python-package/scholarly).
Unfortunately, this issue is outside of my control and would need to be addressed by the package's developers.
